##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.0.0] date: [Tue Apr 16 00:40:52 CST 2019]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#
# ------------------------------------------------

######################################
# target
######################################
TARGET = FreeRTOS-ESP8266-AT-lib


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og

OPENOCD_HOME?=/PATH/TO/YOUR_OPENOCD_INSTALL
OS_NAME?=FreeRTOS

#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Src/stm32f4xx_it.c \
Src/stm32f4xx_hal_msp.c \
Src/stm32f4xx_hal_timebase_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Src/system_stm32f4xx.c \
Src/FreeRTOS/Source/portable/MemMang/heap_4.c \
Src/FreeRTOS/Source/portable/GCC/ARM_CM4_MPU/port.c \
Src/FreeRTOS/Source/croutine.c      \
Src/FreeRTOS/Source/event_groups.c  \
Src/FreeRTOS/Source/list.c          \
Src/FreeRTOS/Source/queue.c         \
Src/FreeRTOS/Source/stream_buffer.c \
Src/FreeRTOS/Source/tasks.c         \
Src/FreeRTOS/Source/timers.c        \
Src/ESP_AT_parser/src/api/esp_misc.c    \
Src/ESP_AT_parser/src/api/esp_ping.c    \
Src/ESP_AT_parser/src/api/esp_sta.c     \
Src/ESP_AT_parser/src/api/esp_ap.c      \
Src/ESP_AT_parser/src/api/esp_conn.c    \
Src/ESP_AT_parser/src/esp/esp.c         \
Src/ESP_AT_parser/src/esp/esp_cmd.c     \
Src/ESP_AT_parser/src/esp/esp_recv_buf.c  \
Src/ESP_AT_parser/src/esp/esp_parser.c    \
Src/ESP_AT_parser/src/esp/esp_pktbuf.c    \
Src/ESP_AT_parser/src/esp/esp_util.c      \
Src/ESP_AT_parser/src/esp/esp_thread.c 



# ASM sources
ASM_SOURCES =  \
startup_stm32f446xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
DUMP = $(GCC_PATH)/$(PREFIX)objdump
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
DUMP = $(PREFIX)objdump
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F446xx 



# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-ISrc/FreeRTOS/Source/include \
-ISrc/FreeRTOS/Source/portable/GCC/ARM_CM4_MPU \
-ISrc/ESP_AT_parser/inc


#### different files for different underlying operating system.
ifeq ($(OS_NAME), FreeRTOS)
    C_SOURCES += Src/ESP_AT_parser/src/system/esp_system_freertos.c
endif

#### ------------------------------------------------------------------
#### ---- different files & paths for unit test, integration test -----
#### ------------------------------------------------------------------
ifeq ($(UNIT_TEST), yes) 
# TODO: complete unit test after completing integration tests.
else
    ifeq ($(INTEGRATION_TEST), yes)
        C_SOURCES += \
            Src/tests/testlogger.c \
            Src/Third_Party/Unity/src/unity.c \
            Src/Third_Party/Unity/extras/fixture/src/unity_fixture.c \
            Src/tests/integration/ESP_AT_parser/port/stm32f446_nucleo_hal.c \
            Src/tests/integration/ESP_AT_parser/common.c                \
            Src/tests/integration/ESP_AT_parser/connect_ap_ping.c       \
            Src/tests/integration/ESP_AT_parser/http_server.c           \
            Src/tests/integration/ESP_AT_parser/mqtt_client.c           \
            Src/tests/integration/ESP_AT_parser/mqtt/mqtt_client_conn.c	\
            Src/tests/integration/ESP_AT_parser/mqtt/mqtt_packet.c      \
            Src/tests/integration/ESP_AT_parser/mqtt/mqtt_sys.c         \
            Src/tests/integration/ESP_AT_parser/test_runner.c           \
            Src/tests/integration/integration_test_entry.c           
        C_INCLUDES += \
            -ISrc/Third_Party/Unity/src \
            -ISrc/Third_Party/Unity/extras/fixture/src
        C_DEFS += -DINTEGRATION_TEST
        ifeq ($(TESTNAME), ping)
            C_DEFS += -DESP_TEST_PING
        else
            ifeq ($(TESTNAME), http_server)
                C_DEFS += -DESP_TEST_HTTP_SERVER 
            else
                ifeq ($(TESTNAME), mqtt_client)
                    C_DEFS += -DESP_TEST_MQTT_CLIENT 
                endif #### end of TESTNAME
            endif #### end of TESTNAME
        endif #### end of TESTNAME
    else
        C_SOURCES += Src/main.c 
    endif #### end of INTEGRATION_TEST
endif #### end of UNIT_TEST




# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -Wint-to-pointer-cast

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F446RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).text $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR)/%.text: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(DUMP) -Dh $< > $@

$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)



#######################################
# execute/debug in the tests
#######################################
dbg_server:
	@openocd -f $(OPENOCD_HOME)/tcl/board/st_nucleo_f4.cfg \
                 -f $(OPENOCD_HOME)/tcl/interface/stlink-v2-1.cfg \
                 -c init -c "reset init"

dbg_client:
	@gdb-multiarch -x ./test_utility.gdb

#######################################
# help documentation
#######################################
help:
	@echo "                                                      ";
	@echo " ---------------- Help Documentation -----------------";
	@echo "                                                      ";
	@echo " Options for building image, running, and debugging   ";
	@echo "                                                      ";
	@echo " * make INTEGRATION_TEST=yes TESTNAME=<test_name> OS_NAME=<os_name>  ";
	@echo "   Build image to run specified integration tests.    ";
	@echo "   where <test_name> can be 'ping' or 'http_server'   ";
	@echo "                                                      ";
	@echo "   <os_name> : ";
	@echo "   so far we only integrate FreeRTOS to the ESP parser";
	@echo "   please refer to src/system/esp_system_freertos.c   ";
	@echo "   in order to port the ESP AT parser within your OS. ";
	@echo "                                                      ";
	@echo " * make dbg_server OPENOCD_HOME=/PATH/TO/YOUR_OPENOCD ";
	@echo "   launch debug server, we use OpenOCD (v0.10.0) here ";
	@echo "   . Note that superuser permission would be required ";
	@echo "   when running openOCD, the command differs & depends";
	@echo "   on your working Operating System.                  ";
	@echo "                                                      ";
	@echo " * make dbg_client                                    ";
	@echo "   launch GDB client to load image, set breakpoints,  ";
	@echo "   watchpoints for execution. We use gdb-multiarch    ";
	@echo "   (v7.7.1 or later) at here.                         ";
	@echo "                                                      ";
	@echo " * make clean                                         ";
	@echo "   clean up the built image                           ";
	@echo "                                                      ";
	@echo "                                                      ";


# *** EOF ***
